# Nombre del servicio para identificacion dentro del ecosistema.
spring.application.name=anpa-shopping-service

# Config Server (Inicio)

# Nombre del perfil remoto que se usara para buscar la configuracion en el Config Server.
# Si no se define, Spring va a usar el valor de spring.profiles.active como perfil para buscar la configuracion remota.
# Recordar que, aunque spring.profiles.active no este definida explicitamente, Spring interpreta la variable de entorno SPRING_PROFILES_ACTIVE.
spring.cloud.config.profile=${SPRING_PROFILES_ACTIVE}

# Activa la importacion de configuracion desde un servidor de configuracion remoto (Spring Cloud Config Server).
spring.config.import=configserver:

# Config Server (Fin)